spring:
  application:
    name: gateway-service
  cloud:
    inetutils:
      timeout-seconds: 5
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway